RGB_MATRIX_ENABLE  	= no
MOUSEKEY_ENABLE    	= no
TAP_DANCE_ENABLE   	= no
CONSOLE_ENABLE		= no

RGBLIGHT_ENABLE    	= yes
OLED_ENABLE 	  	= yes
OLED_DRIVER			= SSD1306
EXTRAKEY_ENABLE   	= yes
WPM_ENABLE		  	= yes

EXTRAFLAGS += -flto

