#! /bin/sh

# Displays configuration.
xrandr --output eDP-1 --off
xrandr --output DP-2 --mode 2560x1440 --rate 74.92 --primary
xrandr --output DP-1 --mode 1920x1080 --rate 84.90 --right-of DP-2
xrandr --output DP-1 --pos 2560x300

# Sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Polybar
$HOME/.config/polybar/launch.sh

# Nitrogen
nitrogen --restore &

# Java fix
wmname LG3D

# Picom
picom -f &
picom --experimental-backends &

# Cursor fix
xsetroot -cursor_name left_ptr &

# Bspwm
bspc monitor DP-2 -d 1 2 3 4
bspc monitor DP-1 -d 8 9 0
bspc monitor DP-2 -s DP-1

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_disabled_monitors     true
bspc config remove_unplugged_monitors   true

bspc config focus_follows_pointer   true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
